### ISSUE TITLE
主题无法导入

### ISSUE THREAD

**Issue by LBShinChan** [qinhua/halo-theme-joe2.0#129]
### 是什么版本出现了此问题？

2.0

### Halo 版本

1.5.3

### 平台

桌面端

### 操作系统

centos

### 描述缺陷

run.halo.app.exception.ThemeNotSupportException: 当前主题仅支持 Halo ^1.5.0 及以上的版本
        at run.halo.app.repository.ThemeRepositoryImpl.attemptToAdd(ThemeRepositoryImpl.java:138) ~[classes!/:1.5.3-SNAPSHOT]
        at run.halo.app.repository.ThemeRepositoryImpl$$FastClassBySpringCGLIB$$e4204deb.invoke(<generated>) ~[classes!/:1.5.3-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at run.halo.app.repository.ThemeRepositoryImpl$$EnhancerBySpringCGLIB$$d91646cd.attemptToAdd(<generated>) ~[classes!/:1.5.3-SNAPSHOT]

**Comment by qinhua** [comment]
@LBShinChan 建议直接用 FTP 工具上传解压后的主题文件夹到指定主题目录解决。
